url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Fellow Huster Blog"
description: "Personal website of uni a student" # the name of your site, e.g. ACME Corp.
email: thuoclarattot@gmail.com
google_analytics_tracking_id:
author: "A Huster"


url: "https://pqceek7.github.io" 
baseurl: "/gellow-huster-blog" 
